#!/bin/bash

# Returns 0 if the script is run with sudo or root, else prompt to rerun with root or sudo
# https://stackoverflow.com/questions/18215973/how-to-check-if-running-as-root-in-a-bash-script
if [[ "$EUID" -ne 0 ]]; then
  echo "Please run this script with sudo"
  exit 1
fi

# Define the file containing the list of packages to install into a variable
package_list="./packages"

# Check if the install-packages file exists
if [[ ! -f "$package_list" ]]; then
  echo "Package list file '$package_list' not found!"
  exit 1
fi

# Read and install each package from the install-packages file
while read -r package; do
  #looks for and installs kakoune and tmux in $package
  echo "Installing $package"
  # skips installation confirmation for pacman
  pacman -S --noconfirm "$package"
# < is used to specify the input file for the while loop
done < $package_list




